const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

// AI Config
const AI_CONFIG = {
  model: 'gpt-4',
  temperature: 0.7,
  max_tokens: 4000
};

// callOpenAI function
async function callOpenAI(prompt, systemPrompt, options = {}) {
  if (!OPENAI_API_KEY) {
    throw new Error('OpenAI API key not configured - using templates');
  }

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENAI_API_KEY}`
      },
      body: JSON.stringify({
        model: options.model || AI_CONFIG.model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: prompt }
        ],
        temperature: options.temperature || AI_CONFIG.temperature,
        max_tokens: options.max_tokens || AI_CONFIG.max_tokens
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error?.message || 'OpenAI API request failed');
    }

    const data = await response.json();
    return data.choices[0].message.content;
  } catch (error) {
    console.error('OpenAI Error:', error);
    throw error;
  }
}

// Resume generators (example - add all from lib/ai.js)
async function generateResume(data) {
  const systemPrompt = `You are an expert resume writer and ATS (Applicant Tracking System) specialist.
Your resumes are:
1. ATS-optimized with proper keywords and formatting
2. Professional, concise, and impactful
3. Using action verbs and quantifiable achievements
4. Properly structured with clear sections
5. Following industry best practices

Create a complete, ready-to-use resume in a professional format.`;

  const prompt = `Create a professional ATS-optimized resume with the following information:

PERSONAL INFORMATION:
- Full Name: ${data.fullName}
- Email: ${data.email}
- Phone: ${data.phone}
- Location: ${data.location || 'Not specified'}
- LinkedIn: ${data.linkedin || 'Not specified'}

PROFESSIONAL SUMMARY:
${data.summary || 'Results-driven professional with proven track record'}

CORE SKILLS:
${data.skills || 'Relevant skills'}

WORK EXPERIENCE:
${data.experience || 'Experience details'}

EDUCATION:
${data.education || 'Education details'}`;

  try {
    return await callOpenAI(prompt, systemPrompt);
  } catch (error) {
    return getTemplateResume(data);
  }
}

// Add all other functions: generateCV, generateCoverLetter, generateRiskAssessment, etc.
async function generateCoverLetter(data) {
  const systemPrompt = `You are an expert cover letter writer.`;
  const prompt = `Write a cover letter for: ${JSON.stringify(data)}`;
  try {
    return await callOpenAI(prompt, systemPrompt);
  } catch (error) {
    return getTemplateCoverLetter(data);
  }
}

// Template fallbacks
function getTemplateResume(data) {
  return `PROFESSIONAL RESUME

${data.fullName || 'John Doe'}
${data.email || 'email@example.com'}

SUMMARY
${data.summary || 'Professional summary...'}

Generated by SAR Trends AI (template fallback)`;
}

// Add all getTemplate* from lib/ai.js
function getTemplateCoverLetter(data) {
  return `Dear Hiring Manager,

I am excited to apply...

Sincerely,
${data.yourName || 'Your Name'}`;
}

// HSE example
async function generateRiskAssessment(data) {
  const systemPrompt = `You are a certified Health and Safety expert.`;
  const prompt = `Create risk assessment for: ${JSON.stringify(data)}`;
  try {
    return await callOpenAI(prompt, systemPrompt);
  } catch (error) {
    return getTemplateRiskAssessment(data);
  }
}

function getTemplateRiskAssessment(data) {
  return `RISK ASSESSMENT

Project: ${data.projectName}

Hazards: ...
Controls: ...

Generated by SAR Trends AI`;
}

// Export all
module.exports = {
  generateResume,
  generateCoverLetter,
  generateRiskAssessment,
  generateRAMS,
  generateWebsite,
  // ... all functions
  getTemplateResume,
  getTemplateCoverLetter,
  // ... all templates
};

