const fs = require('fs-extra');
const path = require('path');
const { PDFDocument, rgb, StandardFonts, PDFFont } = require('pdf-lib');
const { Document, Packer, Paragraph, TextRun, Header, Footer, ImageRun } = require('docx');
const { createCanvas, loadImage } = require('canvas'); // For watermark

const UPLOADS_DIR = path.join(__dirname, '../uploads/documents');

// Ensure directories exist
async function ensureDirs() {
  await fs.ensureDir(UPLOADS_DIR);
  await fs.ensureDir(path.join(UPLOADS_DIR, 'pdf'));
  await fs.ensureDir(path.join(UPLOADS_DIR, 'docx'));
}

// Simple HTML to PDF (multi-page capable)
async function generatePDF(content, title, isFree = false, userName = '') {
  await ensureDirs();
  
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const { width, height } = pdfDoc.context.pageDimensions;
  
  // Add page
  const page = pdfDoc.addPage([width, height]);
  
  // Title
  page.drawText(title, {
    x: 50,
    y: height - 100,
    size: 24,
    font,
    color: rgb(0, 0.53, 0.71),
  });
  
  // Content (wrap text)
  const textLines = content.split('\n').filter(line => line.trim());
  let y = height - 150;
  textLines.forEach(line => {
    if (y < 100) {
      // New page
      page = pdfDoc.addPage([width, height]);
      y = height - 50;
    }
    page.drawText(line, { x: 50, y, size: 12, font, color: rgb(0, 0, 0) });
    y -= 20;
  });
  
  // Watermark for free users
  if (isFree) {
    page.drawText('Generated by SAR Trends AI - Free Plan', {
      x: 50,
      y: height / 2,
      size: 20,
      font,
      color: rgb(0.8, 0.8, 0.8),
      opacity: 0.3,
    });
  }
  
  const pdfPath = path.join(UPLOADS_DIR, 'pdf', `${title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.pdf`);
  const pdfBytes = await pdfDoc.save();
  await fs.writeFile(pdfPath, pdfBytes);
  
  return { name: path.basename(pdfPath), path: pdfPath, type: 'pdf' };
}

// DOCX generation
async function generateDOCX(content, title, isFree = false) {
  await ensureDirs();
  
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          children: [
            new TextRun({
              text: title,
              bold: true,
              size: 32
            })
          ]
        }),
        ...content.split('\n').map(line => new Paragraph({
          children: [new TextRun(line)]
        }))
      ]
    }]
  });
  
  const docxPath = path.join(UPLOADS_DIR, 'docx', `${title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.docx`);
  const buffer = await Packer.toBuffer(doc);
  await fs.writeFile(docxPath, buffer);
  
  return { name: path.basename(docxPath), path: docxPath, type: 'docx' };
}

// TXT
async function generateTXT(content, title) {
  await ensureDirs();
  const txtPath = path.join(UPLOADS_DIR, `${title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.txt`);
  await fs.writeFile(txtPath, content);
  return { name: path.basename(txtPath), path: txtPath, type: 'txt' };
}

// Generate files for document
async function generateDocumentFiles(content, title, docType, isFree, userName) {
  const files = [];
  
  // Always generate PDF and TXT
  files.push(await generatePDF(content, title, isFree, userName));
  files.push(await generateTXT(content, title));
  
  // DOCX for text docs
  if (['resume', 'cover-letter', 'hse'].includes(docType)) {
    files.push(await generateDOCX(content, title, isFree));
  }
  
  return files;
}

module.exports = {
  generateDocumentFiles,
  ensureDirs
};
